/**
 * Inlines the Lucide icons the extension uses into src/ui/icons.ts as SVG
 * strings, from the lucide-static package. Every name is checked against the
 * package at generation time, so a misspelled icon fails here and not on a
 * user's screen. No icon font, no CDN: the extension renders offline.
 */
import { readFileSync, writeFileSync } from 'node:fs';
const NAMES = ['badge-check', 'shield-x', 'shield-alert', 'clock', 'bot', 'archive-x', 'pen-line', 'qr-code', 'x', 'info', 'external-link', 'chevron-right', 'link-2-off', 'mail', 'hash', 'user-round', 'building-2', 'check', 'loader-circle', 'smartphone', 'refresh-cw', 'triangle-alert'];
let out = `// Generated by scripts/make-lucide.mjs from lucide-static ${JSON.parse(readFileSync('node_modules/lucide-static/package.json', 'utf8')).version}. Do not edit.\n// Lucide icons, ISC licence: https://lucide.dev/license\n\nexport const ICONS = {\n`;
for (const n of NAMES) {
  const svg = readFileSync(`node_modules/lucide-static/icons/${n}.svg`, 'utf8').replace(/\n\s*/g, ' ').replace(/<!--.*?-->/g, '').trim();
  out += `  ${JSON.stringify(n)}: ${JSON.stringify(svg)},\n`;
}
out += `} as const;\n\nexport type IconName = keyof typeof ICONS;\n`;
writeFileSync('src/ui/icons.ts', out);
console.log(`${NAMES.length} icons inlined`);
